OWScheduler/urls.py
"""OWScheduler URL Configuration

The `urlpatterns` list routes URLs to views.
Because we specify our views in the scheduler/urls.py, we only need to
specify unrelated views like account management. This also includes a url to
use the autocomplete function in the team admin page.
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from scheduler.views import user_logout, register, \
    TeamAutoComplete, PlayerAutoComplete

urlpatterns = [
    path('admin/', admin.site.urls),  # admin page
    path('', include('scheduler.urls')),  # everything else
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    path('logout/', user_logout, name='user_logout'),  # logout current user
    path('register/', register, name='register'),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='accounts/change_password.html'),
         name='change_password'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/change_password_done.html'),
         name='password_change_done'),

    path('reset-password/', auth_views.PasswordResetView.as_view(
        template_name='accounts/reset_password.html'), name='password_reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    url(r'^/reset/(?P<uidb64>\w*)/(?P<token>[^/]+)/',
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm"),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    url(r'^team-autocomplete/$', TeamAutoComplete.as_view(),
        name='team-autocomplete'),
    url(r'^player-autocomplete/$', PlayerAutoComplete.as_view(),
        name='player-autocomplete'),
    # path('', include('django.contrib.auth.urls')),

]


handler404 = 'scheduler.views.handler404'
handler500 = 'scheduler.views.handler500'
handler403 = 'scheduler.views.handler403'

scheduler/urls.py
"""
Includes all the definitions for urls related to the scheduler app
"""
from django.urls import path

from scheduler import views

app_name = 'scheduler'
urlpatterns = [
    path('', views.home, name='home'),  # home page
    path('players/', views.players, name='players'),  # search for players
    path('players/<str:username>/', views.player_profile,
         name='player_profile'),  # player profile page
    path('players/<str:username>/account/',
         views.account, name='account'),  # edit player account
    path('teams/', views.teams, name='teams'),  # search for teams
    path('players/<str:username>/my-teams/', views.my_teams, name='my_teams'),
    path('teams/<int:teamID>/', views.team_profile,
         name='team_profile'),  # team profile page
    path('teams/<int:teamID>/admin/', views.team_admin, name='team_admin'),
    path('teams/create-team/', views.create_team, name='create_team'),
    path('create-match/', views.create_match, name='create_match'),
    path('edit-match/<int:match_id>/', views.edit_match, name='edit_match'),
    path('create-match/next/<int:match_id>/', views.create_match_next,
         name='create_match_next'),
    path('join_team/<int:teamID>/<str:username>/', views.join_team,
         name='join_team'),
    path('leave_team/<int:teamID>/<str:username>/', views.leave_team,
         name='leave_team'),
    path('delete_team/<int:teamID>/', views.delete_team, name='delete_team')
]

scheduler/models.py
"""
This module controls django's generated database. Each model determines
an entity while each field corresponds to an attribute or relationship. This
controls the information to be stored for each Player, Team, Match, and
TimeSlot.
"""
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class Team(models.Model):
    """
    The Team model identifies an ID and Alias as identifiers.
    Although teams can have the same alias, our database will need a unique ID
    for each.
    """
    teamID = models.IntegerField(primary_key=True)
    teamAlias = models.CharField(max_length=32)
    team_admin = models.ForeignKey('Player', blank=True, null=True,
                                   on_delete=models.SET_NULL,
                                   related_name='team_admin')
    players = models.ManyToManyField('Player', blank=True)
    organization = models.CharField(max_length=50, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.teamAlias) + "#" + str(self.teamID)


class Player(AbstractUser):
    """
    This is the model for Players (users) to store in the database.
    It uses django's AbstractUser which already stores first name, last name,
    email, username, and password. This allows us to use django's secure password
    hashing but still give our users attributes like university, role,
    battletag, sr, and team. The team in this model is an optional foreign key
    that can be null and/or blank. The default string for a player is their
    battletag. It also restricts the roles to either damage, tank, or support.
    """

    # by making these variables, we can access them easier
    # ROLES
    DAMAGE = "Damage"
    TANK = "Tank"
    SUPPORT = "Support"

    ROLE_CHOICES = (
        (DAMAGE, 'Damage'),
        (TANK, 'Tank'),
        (SUPPORT, 'Support'),
    )

    # UNIVERSITIES
    GVSU = 'Grand Valley State University'

    UNIVERSITY_CHOICES = (
        (GVSU, 'Grand Valley State University'),
    )

    university = models.CharField(max_length=100, choices=UNIVERSITY_CHOICES,
                                  blank=True, null=True)

    # damage, tank, or support
    role = models.CharField(max_length=7, choices=ROLE_CHOICES,
                            blank=True, null=True)

    battlenetID = models.CharField("BattleTag", max_length=64,
                                   primary_key=True)
    # USERNAME_FIELD = 'battlenetID'
    # in the future, we may want to use the battletag in place of the username
    # however, this may cause problems for urls

    skillRating = models.IntegerField("SR", null=True, blank=True)

    def __str__(self):
        """
        overriding the default string for a player to their battletag

        :return: player's battletag
        """
        return self.battlenetID


class TimeSlot(models.Model):
    """
    The model for TimeSlot allows users to set their availability.
    The ID avoids the composite key issue from django. Since they don't allow
    composite keys, this is the next best option.
    """
    MON = 0
    TUES = 1
    WED = 2
    THURS = 3
    FRI = 4
    SAT = 5
    SUN = 6

    DAYS_OF_WEEK = (
        (MON, "Monday"),
        (TUES, "Tuesday"),
        (WED, "Wednesday"),
        (THURS, "Thursday"),
        (FRI, "Friday"),
        (SAT, "Saturday"),
        (SUN, "Sunday")
    )

    # alternative solution for composite key
    timeSlotID = models.AutoField(primary_key=True)
    dayOfWeek = models.IntegerField(choices=DAYS_OF_WEEK)
    hour = models.IntegerField(default=0)
    players_available = models.ManyToManyField(Player, related_name=
                                               "player_availabilities")


class Match(models.Model):
    """ Model to store match information. """
    matchID = models.AutoField(primary_key=True)

    CG = "Château Guillard"
    DOR = "Dorado"
    EICH = "Eichenwalde"
    HANA = "Hanamura"
    HOL = "Hollywood"
    HLC = "Horizon Lunar Colony"
    ILI = "Ilios"
    KR = "King's Row"
    LT = "Lijang Tower"
    NEP = "Nepal"
    NUM = "Numbani"
    OAS = "Oasis"
    R66 = "Route 66"
    TA = "Temple of Anubis"
    VI = "Volskaya Industries"
    WG = "Watchpoint: Gibraltar"

    MAP_CHOICES = (
        (CG, "Château Guillard"),
        (DOR, "Dorado"),
        (EICH, "Eichenwalde"),
        (HANA, "Hanamura"),
        (HOL, "Hollywood"),
        (HLC, "Horizon Lunar Colony"),
        (ILI, "Ilios"),
        (KR, "King's Row"),
        (LT, "Lijang Tower"),
        (NEP, "Nepal"),
        (NUM, "Numbani"),
        (OAS, "Oasis"),
        (R66, "Route 66"),
        (TA, "Temple of Anubis"),
        (VI, "Volskaya Industries"),
        (WG, "Watchpoint: Gibraltar"),
    )

    matchMap = models.CharField(max_length=50, choices=MAP_CHOICES,
                                blank=True, null=True)

    # time match is scheduled
    time = models.DateTimeField(default=timezone.now)

    # first team
    # players is distinguished from teams
    # since teams can have more than 6 players
    player_set_1 = models.ManyToManyField('Player',
                                          related_name="player_set_1",
                                          blank=True)
    team_1 = models.ForeignKey('Team', related_name="team_1",
                               on_delete=models.SET_NULL, null=True)

    # second team
    player_set_2 = models.ManyToManyField('Player',
                                          related_name="player_set_2",
                                          blank=True)
    team_2 = models.ForeignKey('Team', related_name="team_2",
                               on_delete=models.SET_NULL, null=True)

    # winner is either team 1 or team 2
    TEAM_1 = 1
    TEAM_2 = 2

    TEAMS = (
        (TEAM_1, 'Team 1'),
        (TEAM_2, 'Team 2'),
    )
    winner = models.IntegerField(choices=TEAMS, blank=True, null=True)

scheduler/forms.py
"""
Controls all the forms generated into HTML by django. This includes editing
instances of models and validating data.
"""
import re

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.forms.models import ModelMultipleChoiceField
from django.forms import ValidationError

from dal import autocomplete

from scheduler.models import Player, Team, Match


class PlayerCreationForm(UserCreationForm):
    """ The form used to create a new player/user """
    username = forms.CharField(label='Enter Username',
                               min_length=4, max_length=150)
    email = forms.EmailField(label='Enter Email')
    battlenetID = forms.CharField(label='Enter BattleTag')

    def clean_username(self):
        """
        Checks the username isn't already in use

        :return: username after validating it is available
        """

        username = self.cleaned_data['username'].lower()
        r = Player.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already exists")
        return username

    def clean_email(self):
        """
        Checks the email isn't already in use

        :return: email after validating it is available
        """
        email = self.cleaned_data['email'].lower()
        r = Player.objects.filter(email=email)
        if r.count():
            raise ValidationError("Email already exists")
        return email

    def clean_battlenetID(self):
        """
        Checks the battlenetID isn't already in use and follows blizzard's
        battletag naming conventions:
        https://us.battle.net/support/en/article/26963

        :return: battlenetID after validating it is available and is a valid
        battletag
        """
        battlenetID = self.cleaned_data['battlenetID'].lower()
        pattern = re.compile("[a-zA-Z][a-zA-Z0-9]{2,11}#[0-9]{4,5}")
        if not pattern.match(battlenetID):
            raise ValidationError("BattleTag is not valid.")
        r = Player.objects.filter(battlenetID=battlenetID)
        if r.count():
            raise ValidationError("BattleTag already in use.")
        return battlenetID

    def save(self, commit=True):
        """ saves the user after assigning the entered battletag """
        user = super(PlayerCreationForm, self).save(commit=False)
        user.battlenetID = self.cleaned_data['battlenetID']
        if commit:
            user.save()
        return user

    class Meta(UserCreationForm):
        model = Player
        fields = (
            'email',
            'username',
            'battlenetID',
            'password1',
            'password2',
        )


class PlayerChangeForm(UserChangeForm):
    """ The form used to change a player's information """
    password = None

    class Meta(UserChangeForm.Meta):
        model = Player
        fields = (
            'first_name',
            'last_name',
            'email',
            'battlenetID',
            'university',
            'role',
            'skillRating',
        )


class CreateTeamForm(forms.ModelForm):
    """ Form that handles creating a team """
    teamID = forms.IntegerField(label="ID")
    teamAlias = forms.CharField(max_length=32,
                            label="Name",
                            help_text="Must be less than 32 characters.")

    def clean_teamID(self):
        """
        Checks if a team ID is already in use

        :return: id that is available for use
        """
        team_id = self.cleaned_data['teamID']
        existing = Team.objects.filter(teamID=team_id)
        if existing.count():
            raise ValidationError("A team with that ID already exists.")
        return team_id

    class Meta:
        model = Team
        fields = ('teamID', 'teamAlias')


class DetailedPlayerModelMultipleChoiceField(ModelMultipleChoiceField):
    """ A class that extends django's ModelMultipleChoiceField
    to display extra attributes in the form's field """
    def label_from_instance(self, obj):
        """
        Adds more detail to the label for each player

        :param obj: player to describe
        :return: a player's battletag and university
        """
        return "%s | %s" % (obj.battlenetID, obj.university)


class TeamAdminForm(forms.ModelForm):
    """A form for a *user* to manage their teams"""
    team_alias = forms.CharField(required=False)
    add_player = forms.ModelChoiceField(
        queryset=Player.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='player-autocomplete'),
        label="Add a Player", required=False
    )
    change_admin = forms.ModelChoiceField(
        queryset=Player.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='player-autocomplete'),
        label="Change Admin", required=False
    )

    def clean_team_alias(self):
        """
        Validates the team alias is url safe in case it needs to be used in
        any url

        :return: an internet safe team alias
        """
        team_alias = self.cleaned_data['team_alias']
        pattern = re.compile(r'^[0-9a-zA-Z\$_\.\+!\*\\\'(),-]*$')
        if not pattern.match(team_alias):
            raise ValidationError("Team name includes invalid characters")
        return team_alias

    class Meta:
        model = Team
        fields = ('team_alias', 'add_player', 'change_admin')
        widgets = {
            'add_player': autocomplete.ModelSelect2(
                url='player-autocomplete'),
            'players':
                autocomplete.ModelSelect2(url='player-autocomplete'),
            'change_admin': autocomplete.ModelSelect2(
                url='player-autocomplete'),
            'players':
                autocomplete.ModelSelect2(url='player-autocomplete')
        }


class TeamDjangoAdminForm(forms.ModelForm):
    """ A form used for *superusers* to manage teams in the admin page. """
    team_admin = forms.ModelChoiceField(
        queryset=Player.objects.all(),
        widget=autocomplete.ModelSelect2(url='player-autocomplete'),
        label="Admin", required=False
    )

    player_autocomplete = forms.ModelMultipleChoiceField(
        queryset=Player.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(
            url='player-autocomplete'),
        label="Players", required=False
    )

    class Meta:
        model = Team
        fields = ('teamAlias', 'teamID', 'team_admin', 'player_autocomplete',
                  'is_active')
        widgets = {'team_admin': autocomplete.ModelSelect2(
                        url='player-autocomplete'),
                   'players': autocomplete.ModelSelect2Multiple(
                       url='player-autocomplete')}


class MatchCreationForm(forms.ModelForm):
    """Manages fields to create a match."""
    class Meta:
        model = Match
        fields = (
            'matchMap',
            # 'time',
            # 'team_1',
            # 'player_set_1',
            # 'team_2',
            # 'player_set_2',
            # 'winner'
        )

scheduler/templates/accounts/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>OWS - Teams</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'scheduler/default.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/change_password.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>

<body id="grad">
<div class="wrapper">
    <div id="header" class="text-center" >
        {% load static %} <img src=" {% static "media/logo.png" %}" style="width: 30%; height: 30%"/>
    </div>

    <div id="body" class="container">
        <h1 class="text-center" style="margin-bottom: 1em;">Change Password</h1>
        <form method="post">
            {% csrf_token %}
        <!-- FORM AND STYLING -->
            <div>
                {{ form.as_p }}
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('input[type=password]').addClass('form-control');
                    });
                </script>
            </div>
        <!-- ERROR STYLING -->
            {% if form.old_password.errors %}
                <style>
                    #id_old_password {
                        border: 1px solid red;
                    }
                </style>
            {% endif %}
            {% if form.new_password1.errors %}
                <style>
                    #id_new_password1 {
                        border: 1px solid red;
                    }
                </style>
            {% endif %}
            {% if form.new_password2.errors %}
                <style>
                    #id_new_password2 {
                        border: 1px solid red;
                    }
                </style>
            {% endif %}
        <!-- SUBMIT -->
            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>

        </form>
    </div>
</div>

scheduler/templates/accounts/change_password_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>OWS - Teams</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'scheduler/default.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/change_password.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>

<body id="grad">
<div class="wrapper">
    <div id="header" class="text-center" >
        {% load static %} <img src=" {% static "media/logo.png" %}" style="width: 30%; height: 30%"/>
    </div>

    <div id="body" class="container text-center">
        <h1 style="margin-bottom: 1em;">Change Password</h1>
        <h6>Your password has been changed successfully.</h6>
        <a class="btn btn-link" href="{% url 'scheduler:home' %}">Go to home page</a>
    </div>
</div>

scheduler/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>OWS - Teams</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'scheduler/default.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/change_password.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>


<body id="grad">
<div class="wrapper">
    <div id="header" class="text-center" >
        {% load static %} <img src=" {% static "media/logo.png" %}" style="width: 30%; height: 30%"/>
    </div>

    <nav id="nav" class="navbar navbar-expand-md sticky-top bg-dark navbar-dark">
        <a class="navbar-brand" href="#">OWS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'scheduler:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'scheduler:teams' %}">Teams</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'scheduler:players' %}">Players</a>
                </li>
                {% if user.is_authenticated and user_teams %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'scheduler:my_teams' username=user.username %}">My Teams</a>
                    </li>
                {% else %}
                    <li class="nav-item"  data-toggle="tooltip" data-placement="top" title="Log in and join a team to view this page!">
                        <a class="nav-link disabled">My Teams</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div id="body" class="container" style="width: 30%;">
        <h1 class="text-center" style="margin-bottom: 1em;">Login</h1>
        <form method="post">
            {% csrf_token %}
            <!-- FORM AND STYLING -->
            <div>
                {{ form.as_p }}
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('input[type=text]').addClass('form-control');
                        $('input[type=password]').addClass('form-control');
                    });
                </script>
            </div>
            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </div>
            <div class="text-center">
                <a class="btn btn-link" href="{% url 'password_reset' %}">Forgot your password?</a>
            </div>
            <!-- ERROR STYLING -->
            {#            {% if form %}#}
            {#                <style>#}
            {#                    #id_email {#}
            {#                        border: 1px solid red;#}
            {#                    }#}
            {#                </style>#}
            {#            {% endif %}#}
            <!-- SUBMIT -->


        </form>
    </div>
</div>

scheduler/templates/accounts/password_reset_confirm.html
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}

scheduler/templates/accounts/password_reset_done.html
<!DOCTYPE html>
<html>
<head>
    <title>OWScheduler</title>
</head>
<body>
    A password reset email has been sent to the entered email, if a user with such an email address exists
</body>
</html>

scheduler/templates/accounts/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>OWS - Teams</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'scheduler/default.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/change_password.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>

<body id="grad">
<div class="wrapper">
    <div id="header" class="text-center" >
        {% load static %} <img src=" {% static "media/logo.png" %}" style="width: 30%; height: 30%"/>
    </div>

    <div id="body" class="container" style="width: 30%;">
        <h1 class="text-center" style="margin-bottom: 1em;">Reset Password</h1>
        <form method="post">
            {% csrf_token %}
        <!-- FORM AND STYLING -->
            <div>
                {{ form.as_p }}
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('input[type=text]').addClass('form-control');
                    });
                </script>
            </div>
        <!-- ERROR STYLING -->
            {% if form.email.errors %}
                <style>
                    #id_email {
                        border: 1px solid red;
                    }
                </style>
            {% endif %}
        <!-- SUBMIT -->
            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>

        </form>
    </div>
</div>